name: build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Test
        run: uv run blog test

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "latest"
          cache: "npm"
          cache-dependency-path: "./theme/package-lock.json"

      - name: Install JS dependencies for the theme
        run: npm install --prefix=./theme

      - name: Synchronize toots
        env:
          MASTODON_CLIENT_ID: ${{ secrets.MASTODON_CLIENT_ID }}
          MASTODON_CLIENT_SECRET: ${{ secrets.MASTODON_CLIENT_SECRET }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        run: uv run blog toots

      - name: Pelican Build
        run: uv run blog build

      - name: "Extra: Notion Feeds"
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: |
          uv run blog notion reading > ./public/reading.xml
          uv run blog notion watching > ./public/watching.xml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: honzajavorek.cz

      - name: Wait for deployment
        run: uv run blog wait
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: uv run blog telegram

      - name: Send to Mastodon
        env:
          MASTODON_CLIENT_ID: ${{ secrets.MASTODON_CLIENT_ID }}
          MASTODON_CLIENT_SECRET: ${{ secrets.MASTODON_CLIENT_SECRET }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        run: uv run blog mastodon

      - name: Save to Git
        uses: EndBug/add-and-commit@v9
        with:
          pull: --rebase --autostash
          add: ./content
          message: "sync ⚙️"
